### ISSUE TITLE
Cannot create directory for Guild

### ISSUE THREAD

**Issue by scionofthevoid** [scionofthevoid/help-ticket-discord-bot#3]
fs.js:922
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir 'C:\ * * * \help-ticket-discord-bot\guilds\\[206505521103110144] bottest'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Object.module.exports.addGuild (C:\ * * * \help-ticket-discord-bot\data\Guild.js:227:6)
    at Object.insert (C:\ * * * \help-ticket-discord-bot\data\TicketCache.js:49:26)
    at Client.<anonymous> (C:\ * * * \help-ticket-discord-bot\index.js:72:14)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at ClientDataManager.newGuild (C:\ * * * \help-ticket-discord-bot\node_modules\discord.js\src\client\ClientDataManager.js:34:21)
    at GuildCreateHandler.handle (C:\ * * * \help-ticket-discord-bot\node_modules\discord.js\src\client\websocket\packets\handlers\GuildCreate.js:17:26)
    at WebSocketPacketManager.handle (C:\ * * * \help-ticket-discord-bot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:120:65)

**Comment by scionofthevoid** [comment]
Guild info files should exist inside help-ticket-discord-bot\\data\\guilds\\<key>, not help-ticket-discord-bot\\guilds\\<key>

**Comment by scionofthevoid** [comment]
Directory is being created correctly. guildInfo.json does not get created.

**Comment by scionofthevoid** [comment]
info.json created correctly, can load from .json files inside a module using require('path').resolve(pathToFile)
